/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package espcoh.ec.edu.producto.Vista;

import espcoh.ec.edu.producto.Constructor.Constructor;
import espcoh.ec.edu.producto.Modelo.GertorProducto;
import espcoh.ec.edu.producto.Modelo.Gestor;

/**
 *
 * @author user
 */
public class Principal extends javax.swing.JFrame {

    private Constructor constructor;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.constructor = new Constructor(new GertorProducto(10), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngDisposición = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        rbnDisponible = new javax.swing.JRadioButton();
        rbnNoDisponible = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        txtNombreProduc = new javax.swing.JTextField();
        txtPrecioProduc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaListaDisponible = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaListaNoDisponible = new javax.swing.JTextArea();
        lblDisponible = new javax.swing.JLabel();
        lblNoDisponible = new javax.swing.JLabel();
        btbVerLista = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblIde = new javax.swing.JLabel();
        txtIde = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Gestor Producto");

        lblNombre.setText("Producto");

        lblPrecio.setText("Precio");

        btngDisposición.add(rbnDisponible);
        rbnDisponible.setText("Disponible");
        rbnDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnDisponibleActionPerformed(evt);
            }
        });

        btngDisposición.add(rbnNoDisponible);
        rbnNoDisponible.setText("No disponible");
        rbnNoDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnNoDisponibleActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txaListaDisponible.setColumns(20);
        txaListaDisponible.setRows(5);
        jScrollPane1.setViewportView(txaListaDisponible);

        txaListaNoDisponible.setColumns(20);
        txaListaNoDisponible.setRows(5);
        jScrollPane2.setViewportView(txaListaNoDisponible);

        lblDisponible.setText("Disponibles");

        lblNoDisponible.setText("No disponible");

        btbVerLista.setText("Ver Lista");
        btbVerLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVerListaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblIde.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNoDisponible)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btbVerLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rbnDisponible)
                        .addGap(18, 18, 18)
                        .addComponent(rbnNoDisponible))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecio)
                            .addComponent(lblNombre)
                            .addComponent(lblIde, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrecioProduc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreProduc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIde)
                    .addComponent(txtIde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecioProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnDisponible)
                    .addComponent(rbnNoDisponible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btbVerLista)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponible)
                    .addComponent(lblNoDisponible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnDisponibleActionPerformed
       // rbnDisponible.setSelected(false);

        //DISPONIBLE
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnDisponibleActionPerformed

    private void rbnNoDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnNoDisponibleActionPerformed
        rbnNoDisponible.setSelected(false);
        //NO DISPONIBLE 
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnNoDisponibleActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Gestor producto = new Gestor();
        producto.setId(Integer.parseInt(txtIde.getText()));
        producto.setNombre(txtNombreProduc.getText());
        producto.setPrecio(Float.parseFloat(txtPrecioProduc.getText()));
        producto.setDisponibilidad(rbnDisponible.isSelected());

        constructor.GestorProducto();
        limpiar();
// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    public int getIde() {
        return Integer.parseInt(txtIde.getText());
    }

    public String getNombre() {
        return txtNombreProduc.getText();

    }

    public String getPrecio() {
        return txtPrecioProduc.getText();

    }

    public boolean getDisponibilidad() {
        return rbnDisponible.isSelected();
    }

   /* public void mostrarMensaje(String mensaje) {
        txaListaDisponible.setText(mensaje);
    }*/

    public void limpiar() {

        txtNombreProduc.setText("");
        txtPrecioProduc.setText("");
        rbnDisponible.setSelected(false);
        rbnNoDisponible.setSelected(false);
        btngDisposición.clearSelection();
    }

    private void btbVerListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVerListaActionPerformed
        Gestor[] productos = constructor.getGertorProducto().listarProductos();
        StringBuilder listaDisponible = new StringBuilder();
        StringBuilder listaNoDisponible = new StringBuilder();

        for (Gestor producto : productos) {
            if (producto != null) {
                if (producto.isDisponibilidad()) {
                    listaDisponible.append("ID :").append(producto.getId()).append("Nombre: ").append(producto.getNombre())
                            .append(", Precio: ").append(producto.getPrecio())
                            .append("\n");
                } else {
                    listaNoDisponible.append("ID :").append(producto.getId()).append("Nombre: ").append(producto.getNombre())
                            .append(", Precio: ").append(producto.getPrecio())
                            .append("\n");
                }
            }
        }

        txaListaDisponible.setText(listaDisponible.toString());
        txaListaNoDisponible.setText(listaNoDisponible.toString());
//VER LISTA
// TODO add your handling code here:
    }//GEN-LAST:event_btbVerListaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // limpiar();
        txtNombreProduc.setText("");
        txtPrecioProduc.setText("");
        txtIde.setText(" ");
        rbnDisponible.setSelected(false);
        rbnNoDisponible.setSelected(false);
        // TODO add your handling code here:   
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbVerLista;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup btngDisposición;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblIde;
    private javax.swing.JLabel lblNoDisponible;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbnDisponible;
    private javax.swing.JRadioButton rbnNoDisponible;
    private javax.swing.JTextArea txaListaDisponible;
    private javax.swing.JTextArea txaListaNoDisponible;
    private javax.swing.JTextField txtIde;
    private javax.swing.JTextField txtNombreProduc;
    private javax.swing.JTextField txtPrecioProduc;
    // End of variables declaration//GEN-END:variables
}
